#ifndef TIMER0_CONFIG_H
#define TIMER0_CONFIG_H

/* Clock source: TIMER0_CLK_INTERNAL or TIMER0_CLK_EXTERNAL */
#define TIMER0_CLK_SOURCE    TIMER0_CLK_INTERNAL

/* Prescaler: TIMER0_PRESCALER_ON or TIMER0_PRESCALER_OFF */
#define TIMER0_PRESCALER     TIMER0_PRESCALER_ON

/* Prescaler divider: TIMER0_PRESCALE_2 .. TIMER0_PRESCALE_256 */
#define TIMER0_PRESCALER_VAL TIMER0_PRESCALE_256

#endif
