#ifndef TIMER0_CONFIG_H
#define TIMER0_CONFIG_H

/* Prescaler Values */

#define TIMER0_PRESCALER_2     0
#define TIMER0_PRESCALER_4     1
#define TIMER0_PRESCALER_8     2
#define TIMER0_PRESCALER_16    3
#define TIMER0_PRESCALER_32    4
#define TIMER0_PRESCALER_64    5
#define TIMER0_PRESCALER_128   6
#define TIMER0_PRESCALER_256   7

#define TIMER0_PRESCALER TIMER0_PRESCALER_256

#endif